// Generated by Xata Codegen 0.28.3. Please do not edit.
import { buildClient } from "@xata.io/client";
import type {
  BaseClientOptions,
  SchemaInference,
  XataRecord,
} from "@xata.io/client";

const tables = [
  {
    name: "project_name",
    columns: [
      { name: "name", type: "string", unique: true },
      {
        name: "description",
        type: "string",
        notNull: true,
        defaultValue: "Fill in",
      },
      { name: "project_id", type: "int", unique: true },
      {
        name: "status",
        type: "string",
        notNull: true,
        defaultValue: "Not Started",
      },
      {
        name: "start_date",
        type: "datetime",
        notNull: true,
        defaultValue: "2020-06-01T08:00:00.000Z",
      },
      { name: "end_date", type: "datetime" },
      {
        name: "adminPages",
        type: "bool",
        notNull: true,
        defaultValue: "false",
      },
    ],
  },
  {
    name: "project_members",
    columns: [
      {
        name: "project_x_id",
        type: "string",
        notNull: true,
        defaultValue: "-1",
      },
      { name: "user_c_id", type: "string", notNull: true, defaultValue: "-1" },
      { name: "approved", type: "bool", notNull: true, defaultValue: "false" },
    ],
  },
  {
    name: "search_string",
    columns: [
      { name: "search_term", type: "string", notNull: true, defaultValue: "1" },
      {
        name: "user_c_id",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
    ],
  },
  {
    name: "project_collaborators",
    columns: [
      { name: "user_id", type: "string", unique: true },
      {
        name: "first_name",
        type: "string",
        notNull: true,
        defaultValue: "johnny",
      },
      {
        name: "last_name",
        type: "string",
        notNull: true,
        defaultValue: "appleseed",
      },
    ],
  },
  {
    name: "search_string_results",
    columns: [
      { name: "title", type: "string" },
      { name: "content_type", type: "string" },
      {
        name: "issue_number",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "issue_type",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "journal_id",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "online_date",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "publication_date",
        type: "datetime",
        notNull: true,
        defaultValue: "now",
      },
      {
        name: "publication_name",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "publication_type",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "publisher",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      { name: "subject", type: "multiple" },
      { name: "url", type: "string", notNull: true, defaultValue: "null" },
      { name: "status", type: "bool" },
      { name: "authors", type: "multiple" },
      { name: "language", type: "string", notNull: true, defaultValue: "null" },
      {
        name: "volume_number",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      {
        name: "search_id",
        type: "string",
        notNull: true,
        defaultValue: "null",
      },
      { name: "abstract", type: "text", notNull: true, defaultValue: "n/a" },
      { name: "doi", type: "string", notNull: true, defaultValue: "null" },
    ],
  },
] as const;

export type SchemaTables = typeof tables;
export type InferredTypes = SchemaInference<SchemaTables>;

export type ProjectName = InferredTypes["project_name"];
export type ProjectNameRecord = ProjectName & XataRecord;

export type ProjectMembers = InferredTypes["project_members"];
export type ProjectMembersRecord = ProjectMembers & XataRecord;

export type SearchString = InferredTypes["search_string"];
export type SearchStringRecord = SearchString & XataRecord;

export type ProjectCollaborators = InferredTypes["project_collaborators"];
export type ProjectCollaboratorsRecord = ProjectCollaborators & XataRecord;

export type SearchStringResults = InferredTypes["search_string_results"];
export type SearchStringResultsRecord = SearchStringResults & XataRecord;

export type DatabaseSchema = {
  project_name: ProjectNameRecord;
  project_members: ProjectMembersRecord;
  search_string: SearchStringRecord;
  project_collaborators: ProjectCollaboratorsRecord;
  search_string_results: SearchStringResultsRecord;
};

const DatabaseClient = buildClient();

const defaultOptions = {
  databaseURL:
    "https://jstarace-s-workspace-ko759t.us-east-1.xata.sh/db/research-papers-db",
};

export class XataClient extends DatabaseClient<DatabaseSchema> {
  constructor(options?: BaseClientOptions) {
    super({ ...defaultOptions, ...options }, tables);
  }
}

let instance: XataClient | undefined = undefined;

export const getXataClient = () => {
  if (instance) return instance;

  instance = new XataClient({
    enableBrowser: true,
    databaseURL:
      "https://jstarace-s-workspace-ko759t.us-east-1.xata.sh/db/research-papers-db",
    apiKey: "xau_GFg5Z5eV9zlaSsN75U8gUOsAS6MF5czZ",
    fetch: fetch,
    branch: "main",
  });
  return instance;
};
